insert Bairro (strNOME,strcep) values ('Jardim bela vista','14150000')
insert Bairro (strNOME,strcep) values ('Centro','14150000')
insert Bairro (strNOME,strcep) values ('Morro','14152000')
insert Bairro (strNOME,strcep) values ('Jardim esperaca','14159000')
insert Bairro (strNOME,strcep) values ('Jardim paulistano','14159000')

insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (1, 'fatima Messias Bezerra',  26, 'f')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (1, 'maria Messias ',          6,  'f')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (1, 'joaquina  Bezerra',       20, 'f')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (1, 'Charles Messias Bezerra', 26, 'M')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (2, 'jukinha  Bezerra',        20, 'M')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (1, 'jose Messias ',           6,  'M')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (3, 'pedro Messias Bezerra',   55, 'M')
insert Cliente (fk_intBairro,strNOME,intIdade,strSexo) values (3, 'antonia Messias Bezerra', 55, 'f')
